### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by FindHao** [chaosmaster/himaul_selinux_permissive#1]
Could you please write a usage about this project?
I read the discussion under the  issue of dirtycow_android. But I'm confused about your discussion. 
I just wanna `mount -o --bind /etc/hosts /myhosts`.
And could you please leave me your email to discuss much more?
Thanks.

**Comment by chaosmaster** [comment]
This project on it's own is just a kernel-module that sets selinux to permissive once loaded.
It has bin tested with HTC M9 (himauhl) but may also work with other 64-bit devices.
on the HTC M9 the module can be loaded from the system_server selinux-context.
In conjunction with dirtycow this can be achieved with hijacking app_process64
